name = "IncompressibleNavierStokes"
uuid = "5e318141-6589-402b-868d-77d7df8c442e"
authors = ["Syver DÃ¸ving Agdestein, Benjamin Sanderse, and contributors"]
version = "0.5.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"

[extensions]
IncompressibleNavierStokesCUDSSExt = ["CUDSS"]

[compat]
Adapt = "3, 4"
CUDA = "5"
CUDSS = "0.2"
CairoMakie = "0.11"
ChainRulesCore = "1"
FFTW = "1"
GLMakie = "0.9"
IterativeSolvers = "0.9"
KernelAbstractions = "0.9"
LinearAlgebra = "1"
Makie = "0.20, 0.21"
NNlib = "0.9"
Observables = "0.5"
Printf = "1"
Random = "1"
SparseArrays = "1"
StaticArrays = "1"
Statistics = "1"
WriteVTK = "1"
julia = "1.9"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
