name = "Examples"
uuid = "318dbb63-4243-420f-99f2-d56058123f9d"
authors = ["Syver DÃ¸ving Agdestein <syverda@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IncompressibleNavierStokes = "5e318141-6589-402b-868d-77d7df8c442e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CairoMakie = "0.12"
FFTW = "1"
GLMakie = "0.10"
IncompressibleNavierStokes = "0.6"
JLD2 = "0.5"
LaTeXStrings = "1"
LinearAlgebra = "1"
Literate = "2"
SparseArrays = "1"
julia = "1.9"

[sources.IncompressibleNavierStokes]
path = ".."
