[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Examples = "318dbb63-4243-420f-99f2-d56058123f9d"
IncompressibleNavierStokes = "5e318141-6589-402b-868d-77d7df8c442e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NeuralClosure = "099dac27-d7f2-4047-93d5-0baee36b9c25"

[compat]
Documenter = "1"
DocumenterCitations = "1"
DocumenterVitepress = "0.1"
Examples = "1"
IncompressibleNavierStokes = "2"
Literate = "2"
NeuralClosure = "1"
julia = "1.9"

[sources.Examples]
path = "../examples"

[sources.IncompressibleNavierStokes]
path = ".."

[sources.NeuralClosure]
path = "../lib/NeuralClosure"
