[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
Examples = "318dbb63-4243-420f-99f2-d56058123f9d"
IncompressibleNavierStokes = "5e318141-6589-402b-868d-77d7df8c442e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NeuralClosure = "099dac27-d7f2-4047-93d5-0baee36b9c25"
